pipeline {
  agent any
  stages {
    stage('building Docker images') {
      steps {
        withCredentials([string(credentialsId: 'database_user', variable: 'dbUser'), string(credentialsId: 'test_db_password', variable: 'dbPassword'), string(credentialsId: 'secret_key', variable: 'secretKey'), string(credentialsId: 'docker_password', variable: 'dockerPassword'), string(credentialsId: 'docker_username', variable: 'dockerUsername')]) {
          sh './scripts/build_docker_images.sh'
        }
      }
    }
    stage('setting up test vm and running tests') {
      steps {
        withCredentials([string(credentialsId: 'docker_password', variable: 'dockerPassword'), string(credentialsId: 'docker_username', variable: 'dockerUsername'), string(credentialsId: 'database_user', variable: 'dbUser'), string(credentialsId: 'test_db_password', variable: 'dbPassword')]) {
          sh './scripts/setup.sh'
          sh './scripts/testing.sh'
        }
      }
    }
    stage('deploy app') {
      steps {
        sh './scripts/deploy.sh'
      }
    }
  }
}

