---
# tasks file for populate-database
- name: 'install mysql-client'
  shell: sudo apt update -y && sudo apt install mysql-client-core-8.0 -y

- name: 'create testdb if not exists'
  shell: mysql -h {{endpoint-address}} -P 3306 -u {{user}} -p{{password}} -e "CREATE DATABASE IF NOT EXISTS testdb;"

- name: 'use testdb'
  shell: mysql -h {{endpoint-address}} -P 3306 -u {{user}} -p{{password}} -e "USE testdb;"
   
- name: 'drop table if exists'
  shell: mysql -h {{endpoint-address}} -P 3306 -u {{user}} -p{{password}} -e "USE testdb; DROP TABLE IF EXISTS users;"

- name: 'create users table'
  shell: mysql -h {{endpoint-address}} -P 3306 -u {{user}} -p{{password}} -e "USE testdb; CREATE TABLE users (userName varchar(30) NOT NULL);"

- name: 'insert values'
  shell: mysql -h {{endpoint-address}} -P 3306 -u {{user}} -p{{password}} -e "USE testdb; INSERT INTO users VALUES ('Bob'),('Jay'),('Matt'),('Ferg'),('Mo');"
   
