---
# tasks file for run-tests
- name: 'docker login'
  shell: echo {{password}} | docker login --username={{username}} --password-stdin

- name: 'pull docker images'
  shell: docker pull {{username}}/frontend:latest && docker pull {{username}}/backend:latest
  
- name: 'create bridge network for containers'
  shell: docker network create app-network

- name: 'run containers'
  shell: docker run --network app-network -d -p 5001:5001 --name backend {{username}}/backend:latest && docker run --network app-network -d -p 5000:5000 --name frontend {{username}}/frontend:latest

- name: 'run backend tests'
  shell: docker exec backend bash -c "pytest tests/ --cov=application" > backend-tests.txt

- name: 'add database uri for frontend tests'
  shell: docker exec backend bash -c "export DATABASE_URI=$(TEST_DATABASE_URI)"

- name: 'run frontend tests'
  shell: docker exec frontend bash -c "pytest tests/ --cov=application" > frontend-tests.txt

- name: 'delete containers and images'
  shell: docker stop frontend backend && docker rmi {{username}}/backend:latest {{username}}/frontend:latest 
  
