apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: production
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: tayop/backend:latest
    ports:
    - containerPort: 5001


apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
