apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: production
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: frontend
        image: tayop/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
