apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  namespace: production
  labels:
    app: flask-app
spec:
  containers:
  - name: frontend
    image: tayop/frontend:latest
    ports:
    - containerPort: 5000


apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
