apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: production
data:
  default.conf:
    server {
        listen 80;
        location / {
            proxy_pass http://flask-app:5000;
        }
    }

